# Generated by Django 5.0.4 on 2024-04-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrations',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
