# Generated by Django 5.0.4 on 2024-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_studentregistrations_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
