# Generated by Django 5.0.4 on 2024-04-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_studentregistrations_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistrations',
            old_name='fullname',
            new_name='username',
        ),
    ]
