# Generated by Django 5.0.4 on 2024-04-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
    ]
