# Generated by Django 5.0.4 on 2024-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
