# Generated by Django 5.0.4 on 2024-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_admin_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_faculties',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_feedback',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admin_dashboard',
            name='total_students',
            field=models.IntegerField(),
        ),
    ]
